### ISSUE TITLE
[feature] 评论区: Vercel toolbar 似乎不能被任意访客所使用

### ISSUE THREAD

**Issue by bzsgbq** [unified-field-theory-org/unifiedfieldtheory.cn#5]
### 测试

首先, 浏览器安装 vercel 插件

然后, 将我在vercel上的网站项目的 Settings 中的 Vercel Toolbar 中的 "Preview Deployments" 和 "Production Deployments" 都设置为 "On"
<img width="1202" alt="image" src="https://github.com/user-attachments/assets/1c6160ed-0906-4111-bfb1-cd629ce7dd81">

之后, 重新部署项目

然后, 访问网站: [tongyichanglun.cn](https://www.tongyichanglun.cn/), 发现是可以使用 vercel toolbar 的
<img width="1197" alt="image" src="https://github.com/user-attachments/assets/2745c68f-3084-44e8-89ff-d04964513a8c">

但是, 访问网站: [unifiedfieldtheory.cn/en/](https://unifiedfieldtheory.cn/en/), 发现无法触发 vercel toolbar, 而且无法看到之前 @obiscr 添加的批注:
<img width="1189" alt="image" src="https://github.com/user-attachments/assets/82a4a58b-85b4-412f-86d1-75d9c5ea985f">

@obiscr 可以测试访问网站 [tongyichanglun.cn](https://www.tongyichanglun.cn/) 时是否可以使用 vercel toolbar

### 调研

**问**: vercel toolbar 哪怕将 Preview Deployments 和 Production Deployments 都调为 On, 也只能被对应的项目所有者和协作者使用吗? 没有办法让任意访客使用吗?

**答 (Claude-3.5-Sonnet):** 
Vercel Toolbar 确实只能被项目的所有者(owner)和协作者(collaborator)使用，这是一个权限控制的设计限制。即使将 Preview 和 Production Deployments 的 toolbar 设置为 On，普通访客也无法看到和使用这个工具栏。

这样设计的主要原因是:
- 安全考虑 - toolbar 包含了项目的部署信息和开发工具
- 功能限制 - 很多功能(如切换部署版本)需要 Vercel 账号权限

如果你希望让访客也能预览不同的部署版本，可以考虑这些替代方案：
- 为每个部署创建独立的预览链接，手动分享给需要的人
- 实现自己的版本切换UI，通过URL参数或其他方式切换不同部署版本
- 使用 Vercel 的 API 构建自定义预览系统

**问**: 我是希望任意访客都可以对文档中的每一段添加批注/评论之类

**答 (Claude-3.5-Sonnet):** 
明白了，如果是为了让访客能对文档内容进行评论和批注，有以下几个方案可以考虑：

1. Giscus
- 基于 GitHub Discussions 的评论系统
- 可以为每个页面或段落创建独立的讨论主题
- 访客使用 GitHub 账号登录即可评论
- 完全开源且免费

2. Utterances
- 类似 Giscus，但基于 GitHub Issues
- 更轻量级，功能相对简单

3. 自定义解决方案
```html
<div class="paragraph">
  <p>这是文档内容...</p>
  <div class="annotation-button" onclick="toggleAnnotation(this)">
    添加批注
  </div>
  <div class="annotation-panel" style="display:none">
    <textarea placeholder="输入你的批注..."></textarea>
    <button onclick="saveAnnotation(this)">保存</button>
  </div>
</div>

<style>
.paragraph {
  position: relative;
  margin: 1em 0;
}
.annotation-button {
  position: absolute;
  right: -30px;
  cursor: pointer;
  color: #666;
}
.annotation-panel {
  margin-top: 10px;
  padding: 10px;
  border: 1px solid #ddd;
}
</style>
```

4. 开源评论系统
- Commento
- Isso
- Remark42

这些方案都不需要 Vercel toolbar，可以让任意访客参与互动。你可以根据具体需求选择：
- 如果想快速实现且依赖 GitHub 生态，推荐 Giscus
- 如果想完全自主控制体验，可以考虑自定义方案
- 如果需要独立部署的成熟系统，可以选择开源评论系统

需要我详细说明某个具体方案吗？

### 结论

vercel toolbar 似乎只有vercel网站项目的所有者和协作者才能使用, 因此似乎要想其他办法实现 "评论区 or 随文批注" 这个功能了

**Comment by obiscr** [comment]
感谢你提供如此详细的调研信息。既然如此，在目前可用的方案中，我更倾向于 Giscus，但是因为之前讨论的问题。具体加不加底部的评论区，暂时还不明确。

**Comment by bzsgbq** [comment]
同意.
